hawtio/hawtio-online

pom.xml

This is to allow them to be overridden from the command line in case the production and community builds differ.

Added a property for yarn install arguments

---

docker/Dockerfile
docker/licenses/licenses.css
docker/licenses/licenses.html
docker/licenses/licenses.xml
docker/licenses/mit.txt
docker/licenses/nginx.txt

This is an attempt to add licenses to the hawtio-online docker image - I'm not sure this is the right way to go about it, but I figured I'd give it an initial shot.    This approach uses a few static files, but I'm not familiar enough with hawtio to know what else we need to list - do we need to list every node.js dependency?
This is a node license reporter from productization that could be used, but the package.json in hawtio-online doesn't contain dependencies, and a license entry also needs to be added : 
https://docs.engineering.redhat.com/display/JPC/Product+Licensing+Information#ProductLicensingInformation-nodejs_license_reporterNode.jsLicenseReporter

Add licenses to docker image.

---

Dockerfile
README.md
deployment-cluster-rbac.yml
deployment-namespace-rbac.yml
docker/.dockerignore
docker/ACL.yaml
docker/Dockerfile
docker/js-yaml.js
docker/nginx-gateway.conf
docker/nginx.js
docker/nginx.repo
docker/nginx.sh
docker/rbac.js
docker/test.js
docker/test.listMBeans.json
oauthclient.yml
packages/common/src/management/management.service.ts

This PR adds RBAC to the management endpoint, i.e., the ability to control access to the Jolokia endpoints based on roles.
See https://issues.redhat.com/browse/ENTESB-8065 for more details.
TODO:

feat: Add RBAC support

---

scripts/generate-certificate.sh

The script pulls sensitive secrets from the cluster but doesn't
clean up afterwards.
This change will use a temporary directory that will be deleted
once the script exits.

Ensure cleanup (sensitive) files used to generate TLS cert

---

package.json
packages/common/package.json
packages/common/src/openshift/openshift.service.ts
yarn.lock

This allows a user to pass a `projectSelector` with the 
hawtconfig.json.
The string needs to be in the same format as the kubectl/oc
`-l` cli arg.
Example:
```
{
"online": {
"projectSelector": "environment=dev,networkzone=internal"
},  
"about": {
"title": "Red Hat Fuse Console",
"productInfo": [], 
"additionalInfo": "The Red Hat Fuse Console eases the discovery and management of Fuse applications deployed on OpenShift.",
"copyright": "", 
"imgSrc": "../online/img/Logo-RedHat-A-Reverse-RGB.png"
}
... 
}
```
Depends on hawtio/hawtio-kubernetes-api#15 and hawtio/hawtio-core#44
Ref ENTESB-14539 and hawtio/hawtio-online#64

Allow to filter projects with a label selector

---

Dockerfile
docker/Dockerfile
docker/nginx.repo

@cunningt Could you have a look at this?  Especially on whether the usage of the nginx versions is ok from productisation point of view. I was hinted that the previous usage of the mainline 1.17 version (instead of this stable) might have been due to productisation issues.
```
ENV NGINX_VERSION 1.18.0-1.el8
ENV NGINX_MODULE_NJS_VERSION 1.18.0.0.4.3-1.el8
```

feat(docker): move Docker image to UBI RHEL 8 #80

---

Dockerfile
docker/nginx-gateway.conf.template
docker/nginx.sh

https://issues.redhat.com/browse/ENTESB-16897
@astefanutti Could you please review it?  It's introducing env vars that do performance tuning for nginx to hawtio-online image.
Once it's merged then I'll accommodate hawtio-operator to those new parameters.

feat(docker): ENTESB-16897 - provide nginx performance tuning via env vars

---

.github/workflows/stale.yml

Added a github action stale which adds tags to the PR's and issues with over a year of inactivity. They are automatically closed after 14 days of adding the stale tag. The entire repository gets checked at 12:00 AM GMT.

chore: added gh action stale

---

.dockerignore
.github/workflows/test.yml
Dockerfile
package.json

* .dockerignore
* adds the patch for js-yaml
* Dockerfile
* Updates the build instructions to include the building of nginx.js
* package.json
* Adds the requisite commands for building
* .github/workflows/test.yml
* Updates versions of node to match hawtio/next (and rollup version is not compatible with < node 14)
* Updates versions of nginx and njs to 1.24

fix: Fixes github test build

---

docker/test.js

- Executing tests on github, even if they fail the test suite has a 0 exit code so everything is green.
- Updates the test script to throw an error if there is a failure and the script exit's 1 instead
- Pass into the report function the expected result status code to compare with the actual which then determines if there is a failure.
See #152 for discussion

fix: Updates njs tests to return a failure

---

docker/osconsole/config.sh
oauthclient.yml
package.json
scripts/kube-apply.sh

- list-projects scope permission for cluster install config
- Corrects install yarn executions to deal with new patches directory

Pick latest changes from 2.x branch

---

.github/workflows/audit.yml
.github/workflows/test.yml

This adds a new workflow 'Audit', which runs weekly on every Sunday to periodically audit the dependencies. It also inserts an audit step to Test workflow, so that every pull request is also audited against the potentially added dependencies.

ci: hAWNG-281 apply yarn npm audit to workflow

---

package.json
packages/kubernetes-api-app/package.json
packages/kubernetes-api-app/webpack.config.js
packages/kubernetes-api/package.json
packages/management-api-app/package.json
packages/management-api-app/webpack.config.js
packages/management-api/package.json
packages/oauth-app/package.json
packages/oauth-app/webpack.config.js
packages/oauth/package.json
packages/oauth/src/form/form-service.ts
packages/oauth/src/openshift/osoauth-service.ts
packages/oauth/src/openshift/support.ts
packages/online-shell/package.json
packages/online-shell/webpack.config.common.js
yarn.lock

- Supercedes https://github.com/hawtio/hawtio-online/pull/190 and ensures that code compiles correctly by changing the monkey patching of window.fetch to a fetch intercepter.
- Supercedes #197 by breaking down into requisite concerns.

Upgrade node 18

---

packages/management-api/src/managed-pod.ts
packages/management-api/src/management-service.ts
packages/online-shell/src/discover/Discover.css
packages/online-shell/src/discover/Discover.tsx
packages/online-shell/src/discover/DiscoverPodItem.tsx
packages/online-shell/src/discover/context.ts

* management-service.ts
* The management service is responsible for emitting an update on all the pods being managed or not. However, no update is emitted if there are no pods. As a result, the Discover component has to assume there are no pods while waiting for them.
* To allow for the Discover component to wait for the update (showing 'loading'), fire an update when there are no pods
* Also for each pod add a flag to show that it has now been 'managed'
* context.ts
* Differentiate between initialising / mounting of the context and the first call to organising the pods and the later mgmt service listener
* Once mounted, only when the listener receives its first update will the context signal it is loaded (that signal will be either when there are pods or not hence the mandated firing …

fix: Stops displaying no containers page while waiting for pods #210

---

packages/kubernetes-api/src/index.ts
packages/management-api/src/index.ts
packages/oauth/src/index.ts
packages/online-shell/package.json
yarn.lock

* kubernetes-api, management-api, oauth
* Remove unnecessary about additions from internal packages
* online-shell
* Adds replace-version command to package and modifies build command to include it.

fix: Substitute placeholder for real version in About box #211

---

Makefile
deploy/base/deployment.yml
package.json

* deployment.yml
* Updates image property to point to quay.io
* package.json
* Updates companion commands to point to quay.io
* Makefile
* Makes VERSION parameter overrideable from ENV
* Updates IMAGE_NAME to quay.io
* Adds VERSION override that updates SNAPSHOT suffix with date timestamp
* Removes clutter of bundle-making as only applicable to operator

fix: Moves default image registry to quay.io #132

---

packages/online-shell/public/hawtconfig.json
packages/online-shell/webpack.config.common.js
packages/online-shell/webpack.config.dev.js

* Aligns the online-shell dev server with the production build by making the documentBase of the app /online.
* Avoids the problem, reported in #242, of an invalid double-slash url since the documentBase is identified as /online.
* hawtconfig.json
* Corrects urls for hawtio-logo not showing up correctly in dev with documentBase but still showing up correctly in production
* webpack.config.common.js
* Does not effect production but make publicPath always /online regardless of mode
* webpack.config.dev.js
* Modifies output and static to include the publicPath
* Updates the osconsole url which is the only path relative in the code base so needs the publicPath prepended

fix: Move online-shell dev env to /online documentBase - #242

---

Dockerfile

* Node image already contains yarn so no need to install it

fix: use official node 18 image #260

---

.gitleaks.toml
.snyk
deploy/script/generate-proxying.sh
deploy/script/generate-serving.sh
docker/nginx.sh
packages/kubernetes-api/src/client/ws-handler.ts
packages/oauth-app/webpack.config.js
packages/oauth/src/form/jwt-decode.test.ts

* .gitleaks.toml
* Provides an extension config which lists the false-positives that should be ignored
* generate-.*\.sh
* Fixes shellcheck warnings is assignments
* nginx.sh
* Removes pipefail setting as non-POSIX and since pipes not actually used in script then removed entirely
* Replaces bash (-v) which POSIX compatible equivalent
* ws-handler.ts
* Checks the origin of the MessageEvent. Since the messages are expected from the cluster they should only comes from ${APP_HOST}/master so any other origin is not appropriate so should be ignored
* .snyk
* Exclude non-production files from snyk analysis

HAWNG-395: Handle warnings and false-positives

---

packages/online-shell/package.json
packages/online-shell/webpack.config.dev.js
yarn.lock

* Provides a treemap served via its own webserver to display the relative sizes of the constituent components of the app
* package.json
* Adds two commands that execute different analyses of the components. Both execute using the dev webpack-config but the second uses the 'production' mode to demonstrate what the chunk size looks like in the final build
* webpack.config.dev.js
* Adds the bundle analyzer plugin and keeps the prod version clean of developer monitoring plugins

chore: Adds bundle analyzer to monitor size of dependencies

---

docs/create-user.md

The way token can be accessed has been changed since Kubernetes 1.24+. See:
- https://github.com/kubernetes/dashboard/commits/master/docs/user/access-control/creating-sample-user.md
- https://github.com/kubernetes/dashboard/pull/6967

docs: update create-user.md

---

packages/kubernetes-api/jest.config.ts
packages/kubernetes-api/package.json
yarn.lock

* Only included to satisfy jest configuration when importing @hawtio/react. By updating the path in jest configuration we can avoid the need to include entirely.

chore: Remove react-markdown from kubernetes-api

---

docker/nginx.sh
docker/osconsole/config.sh
packages/kubernetes-api-app/.env.defaults
packages/kubernetes-api-app/.env.example
packages/kubernetes-api-app/webpack.config.js
packages/management-api-app/.env.defaults
packages/management-api-app/.env.example
packages/management-api-app/webpack.config.js
packages/oauth-app/.env.defaults
packages/oauth-app/.env.example
packages/oauth-app/webpack.config.js
packages/oauth/src/form/form-service.ts
packages/oauth/src/globals.ts
packages/oauth/src/oauth-service.ts
packages/online-shell/.env.defaults
packages/online-shell/.env.example
packages/online-shell/webpack.config.dev.js

Asks the Openshift cluster for the username associated with the given token.
If using form-login and connecting to Openshift, it is possible to obtain the username associated with the login token using the OS REST API.
Adds a small function to the `form-service.ts` that fetches the username upon successful login.

Stops display of the token if not JWT and if Openshift cluster fetches the username from the master API

---

packages/oauth/src/form/form-service.ts
packages/oauth/src/oauth-service.ts
packages/oauth/src/openshift/osoauth-service.ts

The code refactoring also accidentally fixes a potential issue with OSOAuthService that OSOAuth doesn't unregister fetch interception upon logout.

fix(oauth): refactor oauth services and potential fix for logout issue

---

packages/kubernetes-api-app/package.json
packages/kubernetes-api/jest.config.ts
packages/kubernetes-api/package.json
packages/kubernetes-api/src/__mocks__/oauth4webapi.js
packages/management-api-app/package.json
packages/management-api/package.json
packages/oauth-app/package.json
packages/oauth/package.json
packages/online-shell/package.json
scripts/update-hawtio-react.sh
yarn.lock

This also means now hawtio-online supports Camel model 4.0.x and 4.4.x, dropping 3.x support.

feat: upgrade @hawtio/react to 1.1.0

---

docker/nginx-gateway.conf.template
package.json
packages/online-shell/src/bootstrap.tsx
packages/online-shell/src/console/InitLoading.tsx
packages/online-shell/webpack.config.prod.js
yarn.lock

This significantly reduces the size of the two biggest bundles, the most significant change is from 11 MB to 2 MB.

build: use compression for big modules & configure NGINX to use them

---

packages/management-api-app/src/ManagementPods.tsx
packages/management-api/src/jolokia-response-utils.ts
packages/management-api/src/managed-pod.ts
packages/management-api/src/management-service.ts
packages/online-shell/src/discover/Discover.css
packages/online-shell/src/discover/DiscoverPodConnect.tsx
packages/online-shell/src/discover/DiscoverPodItem.tsx
packages/online-shell/src/discover/context.ts
packages/online-shell/src/discover/discover-service.ts

- fix: Handle jolokia probe failure (#354)
- managed-pod.ts
-  Extends the error property of Management to store more detail of errors, ie. messsage and http code
- error property returned to undefined upon successful connection
- Modifies the probe function to store the errors that may be generated
- management-service.ts
- Moves search into managed-pod
- DiscoverPodConnect.tsx
- Adds Error section to display error failure
- Disables the connect button if a mgmt error has occurred
- DiscoverPodItem.tsx
- If error has occurred then display 'unknown routes' label
- fix: Extends the delay in polling for pods in error
- If a pod cannot be connected to then it has a mgmt error. In that case
don't keep polling it every 2 seconds but double the delay before
trying to connect again.
- …

Handle jolokia connection failure and extending delay when connection errors

---

packages/management-api/src/managed-pod.ts
packages/management-api/src/management-service.ts
packages/online-shell/src/discover/Discover.tsx
packages/online-shell/src/discover/DiscoverToolbar.tsx
packages/online-shell/src/discover/StatusIcon.tsx
packages/online-shell/src/discover/context.ts
packages/online-shell/src/discover/discover-service.ts

* managed-pod.ts
* Adds the fingerprint functions from management-service so that the fingerprint can be cached on the pod.
* Important!! fingerprints the management properties and the original kube pod so that changes to the actual pod can be picked up
* management-service.ts
* Adds the fireUpdate property to the updateQueue so that the queue knows to fire an update if ANY of the pods need to fire an update.
* Therefore if the QUEUE not just the last pod needs to fire an update then it should be fired.
* context.ts
* Merges the 2 useEffects into 1 that both organises pods immediately & upon a management update
* Use Cases:
- Discover is correctly populated on startup
- Discover is correctly populated when re-clicked on
- Discover is correctly updated if a change on a pod occurs in …

fix: Sorts out the updating of the Discover component (#397)

---

packages/kubernetes-api-app/package.json
packages/management-api-app/package.json
packages/oauth-app/package.json
packages/online-shell/package.json
yarn.lock

* Any further increment of @types/react causes compile errors from the Patternfly TableComposable Function Component

Fix: Downgrade @types/react to 18.2.64 (#425)

---

docker/nginx-gateway.conf.template

* The header mandates an HTTPS connection with no initial plain HTTP request/response so ensuring the whole connection is secure.
* While it is inherited but sub-locations, where other add_header properties are defined, it must be re-defined

fix: HAWNG-519 Add the Strict-Transport-Security header to all locations

---

docker/ACL.yaml

Without this the viewer user is not able to connect to an app.

fix: add permission to viewer to access the version endpoint

---

docker/nginx-gateway.conf.template
docker/nginx.js
docker/test.js

* nginx-gateway.conf.template
* Changes the master location to first send it through a javascript guard function that determines if the URI is acceptable. Thereby disallowing requests such as secrets and configmaps.
* nginx.js
* proxyMasterGuard function that checks the given uri against a set of accepted patterns.
* If pattern not found then return a 502 and error message.
* If found then internally redirect to the masterinternal location
* test.js
* Adds tests to check syntax and exercise proxyMasterGuard

fix: HAWNG-475 - Limits access to the cluster API using a whitelist

---

packages/oauth/src/openshift/osoauth-service.ts
packages/oauth/src/utils/urls.ts

* When the logout button is clicked in development mode, the app navigates to /auth/logout, which in turn sets up a redirect_uri to the root uri. However, redirecting preserves the logout uri as the final target uri and ends up displaying a blank page.
* If the current uri is /auth/logout when creating a login then reset it back to / ensuring that the blank page is never displayed and the app correctly logs in.

fix: logging-in should not navigate to auth/logout (#407)

---

packages/online-shell/package.json
packages/online-shell/src/bootstrap.tsx
packages/online-shell/src/constants.ts
packages/online-shell/webpack.config.common.js
packages/online-shell/webpack.config.dev.js
packages/online-shell/webpack.config.prod.js
yarn.lock

* The replace-version of the compiled build directory is not correctly replacing the version placeholder due to it already been compressed in the bundle chunks
* Uses webpack DefinePlugin to inject the version DURING the compile stage of the javascript
* package.json
* Add env parameter to the start and build executions that provides the npm package version
* webpack.config.[...].js
* Carry the PACKAGE_VERSION constant through to the DefinePlugin and set the HAWTIO_ONLINE_PACKAGE_VERSION constant to its value
* constants.ts
* Declare the HAWTIO_ONLINE_PACKAGE_VERSION constant that will be assigned by webpack, assign it to an internal var and export it for use
* bootstrap.tsx
* Import the version constant and assign it to the product info

fix: Use webpack DefinePlugin to inject the package version

---

packages/management-api/package.json
packages/management-api/src/managed-pod.ts
yarn.lock

* When using Jolokia class, need to import the simple API functions from jolokia.js/simple as well as the core jolokia.js

HAWNG-666: jolokia search function not included in imports

---

packages/online-shell/src/console/ConsoleLink.tsx
packages/online-shell/src/discover/Discover.css

Patternfly requires for Buttons to have the `component='a'` attribute to respect the `href` attribute https://www.patternfly.org/components/button#links-as-buttons
Removes the underscore from the preferences dropdown of the first link
Closes #503

Fix console links and remove inconsistent link styling

---

packages/management-api/src/management-service.ts
packages/online-shell/src/discover/DiscoverGroupList.tsx

The pod were overrriden if they were the same name, now namespaces are added as well so the conflicts shouldn't happen anymore.
Closes #510

fix: fix connect plugin overriding pods with same name

---

packages/kubernetes-api-app/package.json
packages/kubernetes-api/package.json
packages/management-api-app/package.json
packages/management-api/package.json
packages/management-api/src/management-service.ts
packages/oauth-app/package.json
packages/oauth/package.json
packages/oauth/src/form/form-service.ts
packages/oauth/src/openshift/osoauth-service.ts
packages/online-shell/package.json
packages/online-shell/webpack.config.dev.js
yarn.lock

* With this upgrade, the transport method of jolokia requests has been changed from jquery to fetch. This meant a number of changes in the development server in order to continue working.
* management-service.ts
* Rather than just blindly connect to a target app, try testing the connection first and if it fails do not change location / open a new browser tab but notify the user with the event service
* oauth/[....]service.ts
* Mandate a Content-Type of application/json when using fetch. Due to CORS this is not possible when actually calling fetch(uri, { headers })
* Ensure when regsitering the fetch interceptor that the headers that have been created are not overwritten by any headers already contained in the requestConfig.
* webpack.config.dev.js
* Re-implements management endpoint to …

fix: Upgrade of hawtio/react to 1.5.0

---

Dockerfile-nginx
docker/includes/clear-storage-headers.conf
docker/includes/security-headers-base.conf
docker/includes/security-headers-common.conf
docker/includes/security-headers-online.conf
docker/nginx-gateway.conf.template

* Rather than repeating add_header directives, use 1-line include directives instead to bring import an additional file
* Makes the include files themselves hierarchical with further includes back to a single base include file

fix: Reduces repetition of headers in nginx config file (#440)

---

docker/gateway/src/gateway-api.ts
docker/gateway/src/jolokia-agent/jolokia-agent.ts
docker/gateway/src/utils.ts

* gateway-api.ts
* Adds response interceptor to proxy to capture the body and mask any ip addresses in the body string
* jolokia-agent.ts
* Before sending back the response, ip addresses are masked in the body
* utils.ts
* Regex matched and replacement function
* Only response that cannot be masked is the responses from the websockets as these are never intercepted by the express server.

Masks IP Addresses in json responses (HAWNG-824)

---

docker/includes/security-headers-online.conf

fix(#502): extend CSP to work with monaco-editor

---

charts/hawtio-online/Chart.yaml
charts/hawtio-online/templates/base/deployment.yml
charts/hawtio-online/values.yaml
deploy/Makefile
deploy/base/deployment.yml
deploy/patches/patch-mask-ip-addresses.yml
docker/gateway/env.development.defaults
docker/gateway/src/gateway-api.ts
docker/gateway/src/utils.test.ts
docker/gateway/src/utils.ts
docs/install/helm-charts.md
docs/install/kustomize.md

* Request by user to not make ip addresses in network traffic responses
* By default, ip address data is replaced with <masked> before being transmitted from the gateway to the client.
* Includes a variableto control this functionality:
* MASK_IP_ADDRESSES

feat(security): If user requires, allow ip addresses to be unmasked #661

---

docker/gateway/src/jolokia-agent/globals.ts
docker/gateway/src/jolokia-agent/jolokia-agent.ts
docker/gateway/src/utils.ts

* globals.ts
* Handle possibility of the object being tested by guard functions being null or undefined
* jolokia-agent.ts
* Rejecting a promise with an object is considered an anti-pattern. Far better to reject with an error. Even better in async functions to throw rather than reject.
* Consistently converts all rejections into SimpleResponseErrors which when caught ensure that the response status, statusText and body properties are captured in both the logs and the json returned by the response.

fix: Improves the error handling and tracing in the gateway
