pom.xml, src/assembly/site-dist.xml
Add a proxy profile for building yarn/npm/node inside of a proxy
=> Add a proxy profile for building yarn/npm/node inside of a proxy

package.json, packages/common/package.json, packages/integration/index.html, packages/integration/package.json, packages/online/index.html, packages/online/package.json, yarn.lock
Upgrade Hawtio dependencies to version 4.10.x
=> Upgrade Hawtio dependencies (master)

package.json, packages/common/package.json, packages/integration/index.html, packages/integration/package.json, packages/online/index.html, packages/online/package.json, yarn.lock
Upgrade Hawtio dependencies to version 4.10.x
=> Upgrade Hawtio dependencies (1.x-redhat-7.x)

.gitignore, README.md, package.json, scripts/generate-certificate.sh
Fix #57
@astefanutti Please review if it's ok or not.
=> chore(install): Provide script to automate client cert generation for OpenShift 4

gulpfile.js
Attempt to fix the local run issue.
@astefanutti Pls review this to quickly check if I'm going the right path.
=> fix(dev): Local run doesn't work with OpenShift 4.x #59

gulpfile.js, packages/common/src/management/management.helper.ts, packages/common/src/management/management.service.ts, packages/common/src/openshift/openshift.service.ts, packages/integration/src/app.module.ts, packages/integration/src/navigation/navigation.service.ts, packages/online/src/app.module.ts, packages/online/src/discover/discover.module.ts, yarn.lock
https://issues.redhat.com/browse/ENTESB-13777
=> ENTESB-13777 - Include Artemis plugin in Fuse Console

README.md, docs/generate-certificates.md, docs/rbac.md
- How to create a ServiceAccount for k8s deployment will be added later.
=> doc(k8s): reorg README and update with the new deployment method #89

deploy/base/deployment.yml, docker/nginx.js, docker/rbac.js, docker/rbac.spec.js
https://issues.redhat.com/browse/ENTESB-16898
=> feat(docker): implement RBACRegistry in hawtio-online image

docker/rbac.js, docker/rbac.spec.js
This implements RBAC decoration along with MBeans list returned from RBACRegistry. It lets the frontend skip the subsequent bulky request to acquire RBAC information, which may have even caused "413 Request Entity Too Large" error when for example a Camel app has 500 routes.
https://issues.redhat.com/browse/ENTESB-16898
=> feat(docker): implement RBACDecorator in hawtio-online image

packages/common/src/openshift/openshift.module.ts, packages/common/src/openshift/openshift.service.ts, packages/online/src/discover/discover.html, packages/online/src/discover/discover.module.ts, packages/online/src/labels/labels.directive.ts, packages/online/src/labels/labels.module.ts
https://issues.redhat.com/browse/ENTESB-17741
=> fix(online): ENTESB-17741 Open pod details leads to Page Not Found

packages/integration/package.json, yarn.lock
https://issues.redhat.com/browse/ENTESB-19684
=> fix(integration): ENTESB-19684 upgrade artemis-plugin to 1.2.3 (Artemis 2.21.0.redhat-00025 / AMQ 7.10.0)

packages/integration/package.json, yarn.lock
https://issues.redhat.com/browse/ENTESB-19967
=> feat(integration): ENTESB-19967 upgrade artemis-plugin to 1.2.4 (Artemis 2.21.0.redhat-00030 / AMQ 7.10.1)

Dockerfile, docker/hawtio-404.html, docker/hawtio-50x.html, docker/nginx-gateway-k8s.conf.template, docker/nginx-gateway.conf.template, docker/nginx.conf
* Avoids revealing type or version of web server used by displaying custom error pages
=> HAWNG-6: Adds custom 404 and 50x error pages

Makefile, packages/oauth/src/openshift/support.ts
* Makefile
* Removes dev comment
* support.ts
* Correct spelling error
=> chore: very minor fixes

deploy/Makefile
* The env var used for OS console url env var name needs correcting. Otherwise, this stops the OS console url becoming active in the app
=> fix: Corrects Makefile install with CONSOLE_URL

packages/kubernetes-api-app/package.json, packages/kubernetes-api/package.json, packages/management-api-app/package.json, packages/management-api/package.json, packages/oauth-app/package.json, packages/oauth/package.json, packages/online-shell/package.json, yarn.lock
* Also upgrades jolokia.js to 2.0.0
=> fix: Upgrades hawtio/react to 1.0.2 #270

packages/kubernetes-api-app/package.json, packages/kubernetes-api-app/webpack.config.js, packages/kubernetes-api/package.json, packages/management-api-app/package.json, packages/management-api-app/webpack.config.js, packages/management-api/package.json, packages/management-api/src/management-service.ts, packages/oauth-app/package.json, packages/oauth-app/webpack.config.js, packages/oauth/package.json, packages/online-shell/package.json, packages/online-shell/webpack.config.common.js, yarn.lock
* Pin victory-core resolution to 36.8.6 to remove warning about react/charts
* management-service.ts
* Fix casting compilation error
* Suppress Critical Dependency expression warning
=> chore: Upgrade @hawtio/react to 1.0.7 (#340)

docker/nginx-gateway.conf.template
=> fix(docker): logout clears entire user settings on preferences

packages/kubernetes-api-app/package.json, packages/kubernetes-api/package.json, packages/kubernetes-api/src/client/client-instance.ts, packages/kubernetes-api/src/index.ts, packages/management-api-app/package.json, packages/management-api/package.json, packages/oauth-app/package.json, packages/oauth/package.json, packages/oauth/src/api.ts, packages/oauth/src/form/form-service.ts, packages/oauth/src/form/globals.ts, packages/oauth/src/form/login/FormAuthLoginForm.tsx, packages/oauth/src/index.ts, packages/oauth/src/oauth-service.ts, packages/oauth/src/openshift/globals.ts, packages/oauth/src/openshift/osoauth-service.ts, packages/online-shell/package.json, packages/online-shell/src/bootstrap.tsx, yarn.lock
https://issues.redhat.com/browse/HAWNG-557
This one is a more lightweight version of HAWNG-557 fix than #377. It might be acceptable for you @phantomjinx .
You can check how it works here:
https://hawtio-online-tasato-test.hawtio-cluster-194953-21cb4c1134e0db6479397e6534459c6a-0000.jp-tok.containers.appdomain.cloud/online/
=> fix(oauth): HAWNG-557 Hawtio login page shows up before OpenShift login page (lite)

docker/nginx-gateway.conf.template
* HAWNG-517 - Adds CSP headers to nginx server
=> Adds CSP header for security in nginx server

package.json, packages/kubernetes-api/jest.config.ts, packages/oauth/package.json, packages/oauth/src/utils/crypto.ts, packages/online-shell/package.json, yarn.lock
Changes needed to make `yarn link <path/to>/hawtio-next/packages/hawtio` work locally.
=> fix(build): successful yarn link to local @hawtio/react

packages/kubernetes-api-app/package.json, packages/kubernetes-api/package.json, packages/management-api-app/package.json, packages/management-api/package.json, packages/management-api/src/jolokia-response-utils.ts, packages/management-api/src/managed-pod.ts, packages/oauth-app/package.json, packages/oauth/package.json, packages/online-shell/package.json, yarn.lock
* Jolokia utils now built-in to 2.2.4 of jolokia replace those functions written in hawtio-online.
=> Replaces jolokia utils with jolokia incorporated versions #396

charts/hawtio-online/Chart.yaml, charts/hawtio-online/templates/base/service.yml, charts/hawtio-online/templates/k8s/ingress.yml, charts/hawtio-online/values.yaml
Hi!
I propose to add customization for service and ingress annotations and service type.
=> Helm chart: add service and ingress annotations and service type

packages/kubernetes-api-app/package.json, packages/management-api-app/package.json, packages/oauth-app/package.json, yarn.lock
* @hawtio/react has not yet upgraded to 7.7.1 so need to revert for the moment.
=> chore: Bring back version of react-router-dom to 6.30.1
